.Dd May 17, 2026
.Dt DOOMMENU 1
.Os
.Sh NAME
.Nm doommenu
.Nd DOOMSDAY menu module
.Sh DESCRIPTION
.Nm
is the named DOOMSDAY module for the customized
.Xr doommenu 1
build. It is used with DoomWM for launching commands and driving desktop
actions.
.Sh INSTALL
.Dl \&./install.sh --menu
.Sh INSTALLED COMMANDS
.Bl -tag -width "doommenu_path"
.It Nm doommenu
Dynamic menu executable.
.It Nm doommenu_run
Launcher helper.
.It Nm doommenu_path
Path cache helper.
.It Nm stest
File-test helper used by doommenu scripts.
.El
.Sh SEE ALSO
.Xr doomsday-system 1 ,
.Xr doomwm 1 ,
.Xr doommenu 1
