.Dd May 17, 2026
.Dt SENTINELSTATUS 1
.Os
.Sh NAME
.Nm sentinelstatus
.Nd DOOMSDAY status module
.Sh DESCRIPTION
.Nm
is the named DOOMSDAY module for the customized
.Xr slstatus 1
build. It provides the status text used by the X11 window-manager bar.
.Sh INSTALL
.Dl \&./install.sh --slstatus
.Sh INSTALLED COMMANDS
.Bl -tag -width "slstatus"
.It Nm slstatus
Status monitor executable.
.El
.Sh SEE ALSO
.Xr doomsday-system 1 ,
.Xr slstatus 1
