name: check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  void:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        libc:
          - glibc
          - musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Void checks
        run: make void-${{ matrix.libc }}
